import {
  createContext,
  useContext,
  useState,
  ReactNode,
} from "react";

export type Language = "en" | "ar" | "am" | "om" | "so";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<
  LanguageContextType | undefined
>(undefined);

export const languages = {
  en: "English",
  ar: "العربية",
  am: "አማርኛ",
  om: "Afaan Oromoo",
  so: "Soomaali",
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({
  children,
}: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error(
      "useLanguage must be used within a LanguageProvider",
    );
  }
  return context;
}

// Translation object
const translations: Record<Language, any> = {
  en: {
    common: {
      back: "Back",
      next: "Next",
      finish: "Finish",
      cancel: "Cancel",
      continue: "Continue",
      submit: "Submit",
      login: "Login",
      logout: "Logout",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      close: "Close",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      language: "Language",
    },
    greeting: {
      assalamu: "Assalamu'alaikum warahmatullahi wabarakatuh",
      arabic:
        "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ",
      meaning:
        "May the peace, mercy, and blessings of Allah be with you",
      welcome: "Welcome to Khendeq",
      peace: "Peace be upon you",
    },
    info: {
      title: "E-Learning Medres",
      bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      bismillahMeaning:
        "In the name of Allah, the Most Gracious, the Most Merciful",
      missionTitle: "Our Mission",
      missionText:
        "Khendeq is a comprehensive Islamic e-learning platform designed to help mothers and caretakers guide their children through a structured journey of Islamic education.",
      feature1Title: "Comprehensive Curriculum",
      feature1Text:
        "10 grade levels, covering Quran, Hadith, Fiqh, Sira, Arabic, Dhikr, and Akhlaq",
      feature2Title: "Mother-Led Learning",
      feature2Text:
        "Empowering mothers to be the primary educators of their children at home",
      feature3Title: "Progress Tracking",
      feature3Text:
        "Monitor your child's achievements and celebrate milestones together",
      feature4Title: "Engaging Content",
      feature4Text:
        "Videos, textbooks, and interactive games to make learning enjoyable",
      whatsIncluded: "What's Included",
      include1: "Daily structured lessons with video content",
      include2: "Comprehensive textbook materials",
      include3: "Interactive games and activities",
      include4: "Progress tracking and achievement system",
      include5: "Notifications and reminders",
      include6: "Personalized profile for each child",
      quoteText:
        "The best among you are those who learn the Quran and teach it.",
      quoteAuthor: "Prophet Muhammad ﷺ (Sahih al-Bukhari)",
      registerButton: "Send a Registration Request",
      getStartedButton: "Get Started",
    },
    registration: {
      step1Title: "Caretaker Information",
      step2Title: "Training Video",
      step1Of2: "Step 1 of 2",
      step2Of2: "Step 2 of 2",
      profilePhoto: "Profile Photo",
      fullName: "Full Name",
      fullNamePlaceholder: "Enter your full name",
      age: "Age",
      agePlaceholder: "Age",
      gender: "Gender",
      genderSelect: "Select",
      female: "Female",
      male: "Male",
      other: "Other",
      role: "Role",
      roleSelect: "Select your role",
      mother: "MOTHER",
      father: "FATHER",
      caretaker: "CARETAKER",
      sibling: "SIBLING",
      otherRole: "OTHER",
      location: "Location",
      continent: "Continent",
      selectContinent: "Select Continent",
      country: "Country",
      countryPlaceholder: "Country",
      contactInfo: "Contact Information",
      email: "Email address",
      emailPlaceholder: "Email address",
      phone: "Phone number (optional)",
      phonePlaceholder: "Phone number (optional)",
      languages: "Languages (Select all that apply)",
      amharic: "AMHARIC",
      english: "ENGLISH",
      arabic: "ARABIC",
      oromo: "OROMO",
      quranLevel: "Quran Level (Juz Completed)",
      suitableTime: "Suitable Time for Guiding Child",
      suitableTimePlaceholder:
        "e.g., Morning 10:00 AM - 12:00 PM",
      expectations: "Your Expectations from Khendeq",
      expectationsPlaceholder:
        "Share your expectations and goals...",
      loginCredentials: "Login Credentials",
      username: "Preferred Username",
      usernamePlaceholder: "Preferred Username",
      password: "Password",
      passwordPlaceholder: "Password",
      credentialsNote:
        "This username and password will be used to login after approval",
      continueStep2: "Continue to Step 2",
      backToStep1: "Back to Step 1",
      trainingRequired: "Training Required",
      trainingRequiredText:
        "To complete your registration request, you must watch the introductory and explanatory training video. This video will help you understand how to effectively use Khendeq to guide your children's Islamic education.",
      videoTitle: "Introduction to Khendeq",
      videoSubtitle:
        "Learn how to guide your children through their Islamic education journey",
      whatYouLearn: "What You'll Learn:",
      topic1: "Platform Overview",
      topic1Desc: "Understanding the Khendeq interface",
      topic2: "Daily Lesson Structure",
      topic2Desc: "How to conduct daily Islamic lessons",
      topic3: "Progress Tracking",
      topic3Desc: "Monitoring your child's achievements",
      topic4: "Best Practices",
      topic4Desc: "Tips for effective home teaching",
      videoCompleted: "Training Completed!",
      videoCompletedText:
        "You're now ready to submit your registration request",
      watchToComplete: "Watch Video to Continue",
      submitRequest: "Submit Registration Request",
      videoPlaying: "Training Video Playing...",
      complete: "Complete",
      videoDialogTitle: "Training Video Required",
      startVideo: "Start Training Video",
      congratulations: "Congratulations!",
      thankYou:
        "Thank you for sending your registration request",
      underReview:
        "Your request is now under review by the Khendeq admin team. We carefully review each application to ensure the best learning experience for all our students.",
      emailNotification: "Email Notification",
      emailNotificationText:
        "We will send your login credentials to your registered email address",
      smsNotification: "SMS Notification",
      smsNotificationText:
        "You may also receive a text message confirmation (if phone number provided)",
      whatHappensNext: "What Happens Next?",
      nextStep1: "Admin team reviews your application",
      nextStep2: "Account approval (within 3 days)",
      nextStep3: "Login credentials sent via email or SMS",
      nextStep4: "Begin your child's Islamic learning journey!",
      stayTuned: "Stay tuned!",
      contactSoon: "We will contact you in the upcoming 3 days",
    },
    login: {
      title: "Login to Continue",
      email: "Email/Phone No/Username",
      emailPlaceholder: "Enter your email/phone no/username",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      loginButton: "Login",
      newUserNote:
        "New users should complete the registration request process and wait for approval",
      seekKnowledge:
        "Seek knowledge from the cradle to the grave",
      islamicTeaching: "Islamic Teaching",
    },
    home: {
      greeting: "Assalamu'alaikum",
      overallProgress: "Overall Progress",
      complete: "Complete",
      activeStudents: "Active Students",
      lessonsThisWeek: "Lessons This Week",
      recentActivity: "Recent Activity",
      upcomingActivities: "Upcoming Activities",
      recentAchievements: "Recent Achievements",
    },
    lesson: {
      selectChild: "Select Child",
      selectGrade: "Select Grade Level",
      selectSemester: "Select Semester",
      selectWeek: "Select Week",
      weeklySchedule: "Weekly Class Schedule",
      dailyClassTimes: "Daily Class Times:",
      firstPeriod: "First Period: 10:30 - 11:20 (Quran)",
      secondPeriod:
        "Second Period: 11:30 - 12:20 (Daily Subject)",
      currentGrade: "Current Grade",
      addChild: "Add New Child",
      weeksOfLessons: "weeks of lessons",
      completePrevious: "Complete previous semester to unlock",
      semesterStructure: "Semester Structure:",
      regularWeeks: "11 weeks of regular lessons",
      revisionWeek: "1 week for revision and test preparation",
      testWeek: "1 week for tests",
      regularLesson: "Week",
      revisionWeekLabel: "Revision Week",
      testWeekLabel: "Test Week",
      weekTypes: "Week Types:",
      regularLearning: "Regular Learning Week",
      revisionPrep: "Revision & Preparation",
      locked: "Locked",
      unlockWeek: "Unlock Week",
      progressSequentially: "Progress Sequentially",
      sequentialText:
        "Complete all lessons in the current week to unlock the next one. This ensures thorough understanding and mastery of each topic.",
      weekLocked: "Week Locked",
      weekLockedText:
        "This week's lessons are currently locked. To access Week {week}, you must first complete all previous weeks.",
      toUnlockWeek: "To unlock Week {week}:",
      completeAllDays: "Complete all 6 days of Week {week}",
      finishAllLessons: "Finish all Quran and subject lessons",
      watchVideos: "Watch all videos and complete games",
      achieveScores: "Achieve minimum passing scores",
      sequentialLearning:
        "Sequential learning ensures your child builds a strong foundation in Islamic knowledge before advancing to new topics.",
      understood: "Understood",
      sequentialLearningDay: "Sequential Learning",
      dayLockedText:
        "Complete today's lesson to unlock tomorrow's classes. Only one day is available at a time to ensure consistent learning progress.",
      lessonLocked: "Lesson Locked",
      dayLessonLocked: "{day}'s lesson is currently locked.",
      toUnlockLesson: "To unlock this lesson:",
      completePreviousDay:
        "Complete the previous day's lessons",
      finishBothPeriods:
        "Finish both Quran and subject periods",
      watchAllVideos:
        "Watch all videos and complete activities",
      strongFoundation:
        "This ensures your child masters each lesson before moving forward, building a strong foundation in Islamic knowledge.",
      active: "Active",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
    },
    progress: {
      title: "Progress Tracking",
      overallProgress: "Overall Progress",
      thisWeek: "This Week",
      achievements: "Achievements",
      rank: "Rank",
      weeklyActivity: "Weekly Activity",
      chartComing: "Activity chart coming soon",
    },
    notification: {
      title: "Notifications",
      markAllRead: "Mark all as read",
      unreadNotifications: "Unread Notifications",
      noNotifications: "No notifications",
      allCaughtUp: "You're all caught up!",
      lessonCompleted: "Lesson Completed",
      newWeekUnlocked: "New Week Unlocked",
      dailyReminder: "Daily Reminder",
      achievementUnlocked: "Achievement Unlocked",
    },
    profile: {
      title: "Profile",
      memberSince: "Member since",
      email: "Email",
      location: "Location",
      languages: "Languages",
      quranLevel: "Quran Level",
      completed: "Completed",
      myChildren: "My Children",
      settings: "Settings",
      helpSupport: "Help & Support",
      logout: "Logout",
      quoteText:
        "The best of you are those who learn the Quran and teach it.",
      quoteAuthor: "Prophet Muhammad ﷺ",
    },
    subjects: {
      quran: "Quran",
      hadis: "Hadis",
      fiqh: "Fiqh",
      sira: "Sira",
      arabic: "Arabic",
      zikr: "Zikr",
      akhlaq: "Akhlaq",
    },
  },
  ar: {
    common: {
      back: "رجوع",
      next: "التالي",
      finish: "إنهاء",
      cancel: "إلغاء",
      continue: "متابعة",
      submit: "إرسال",
      login: "تسجيل الدخول",
      logout: "تسجيل الخروج",
      save: "حفظ",
      delete: "حذف",
      edit: "تعديل",
      close: "إغلاق",
      loading: "جاري التحميل...",
      error: "خطأ",
      success: "نجاح",
      language: "اللغة",
    },
    greeting: {
      assalamu: "السلام عليكم ورحمة الله وبركاته",
      arabic:
        "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ",
      meaning: "عليكم السلام ورحمة الله وبركاته",
      welcome: "مرحبا بكم في خندق",
      peace: "السلام عليكم",
    },
    info: {
      title: "E-Learning Medresa",
      bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      bismillahMeaning: "بسم الله الرحمن الرحيم",
      missionTitle: "مهمتنا",
      missionText:
        "��ندق هي منصة تعليمية إسلامية شاملة مصممة لمساعدة الأمهات والمربيات على توجيه أطفالهن عبر رحلة منظمة للتعليم الإسلامي.",
      feature1Title: "منهج شامل",
      feature1Text:
        "10 مستويات دراسية تغطي القرآن والحديث والفقه والسيرة والعربية والذكر والأخلاق",
      feature2Title: "التعلم بقيادة الأم",
      feature2Text:
        "تمكين الأمهات ليكن المعلمات الأساسيات لأطفالهن في المنزل",
      feature3Title: "تتبع التقدم",
      feature3Text:
        "راقبي إنجازات طفلك واحتفلي بالإنجازات معاً",
      feature4Title: "محتوى جذاب",
      feature4Text:
        "مقاطع فيديو وكتب مدرسية وألعاب تفاعلية لجعل التعلم ممتعاً",
      whatsIncluded: "ما هو مشمول",
      include1: "دروس يومية منظمة مع محتوى الفيديو",
      include2: "مواد الكتب المدرسية الشاملة",
      include3: "ألعاب وأنشطة تفاعلية",
      include4: "نظام تتبع التقدم والإنجاز",
      include5: "الإشعارات والتذكيرات",
      include6: "ملف شخصي لكل طفل",
      quoteText: "خيركم من تعلم ��لقرآن وعلمه",
      quoteAuthor: "النبي محمد ﷺ (صحيح البخاري)",
      registerButton: "إرسال طلب التسجيل",
      getStartedButton: "ابدأ الآن",
    },
    registration: {
      step1Title: "معلومات المربي",
      step2Title: "فيديو تدريبي",
      step1Of2: "الخطوة 1 من 2",
      step2Of2: "الخطوة 2 من 2",
      profilePhoto: "صورة الملف الشخصي",
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "أدخل اسمك الكامل",
      age: "العمر",
      agePlaceholder: "العمر",
      gender: "الجنس",
      genderSelect: "اختر",
      female: "أنثى",
      male: "ذكر",
      other: "آخر",
      role: "الدور",
      roleSelect: "اختر دورك",
      mother: "أم",
      father: "أب",
      caretaker: "مربي",
      sibling: "أخ/أخت",
      otherRole: "آخر",
      location: "الموقع",
      continent: "القارة",
      selectContinent: "اختر القارة",
      country: "الدولة",
      countryPlaceholder: "الدولة",
      contactInfo: "معلومات الاتصال",
      email: "عنوان البريد الإلكتروني",
      emailPlaceholder: "عنوان البريد الإلكتروني",
      phone: "رقم الهاتف (اختياري)",
      phonePlaceholder: "رقم الهاتف (اختياري)",
      languages: "اللغات (اختر جميع ما ينطبق)",
      amharic: "الأمهرية",
      english: "الإنجليزية",
      arabic: "العربية",
      oromo: "الأورومو",
      quranLevel: "مستوى القرآن (الأجزاء المكتملة)",
      suitableTime: "الوقت المناسب لتوجيه الطفل",
      suitableTimePlaceholder:
        "مثل: الصباح 10:00 صباحاً - 12:00 ظهراً",
      expectations: "توقعاتك من خندق",
      expectationsPlaceholder: "شاركي توقعاتك وأهدافك...",
      loginCredentials: "بيانات تسجيل الدخول",
      username: "اسم المستخدم المفضل",
      usernamePlaceholder: "اسم المستخدم المفضل",
      password: "كلمة المرور",
      passwordPlaceholder: "كلمة المرور",
      credentialsNote:
        "سيتم استخدام اسم المستخدم وكلمة المرور هذه لتسجيل الدخول بعد الموافقة",
      continueStep2: "متابعة إلى الخطوة 2",
      backToStep1: "العودة إلى الخطوة 1",
      trainingRequired: "التدريب مطلوب",
      trainingRequiredText:
        "لإكمال طلب التسجيل، يجب عليك مشاهدة الفيديو التدريبي التمهيدي والتوضيحي. سيسا��دك هذا الفيديو على فهم كيفية استخدام خندق بفعالية لتوجيه التعليم الإسلامي لأطفالك.",
      videoTitle: "مقدمة إلى خندق",
      videoSubtitle:
        "تعلمي كيفية توجيه أطفالك في رحلة التعليم الإسلامي",
      whatYouLearn: "ما ستتعلمينه:",
      topic1: "نظرة عامة على المنصة",
      topic1Desc: "فهم واجهة خندق",
      topic2: "هيكل الدرس اليومي",
      topic2Desc: "كيفية إجراء الدروس الإسلامية اليومية",
      topic3: "تتبع التقدم",
      topic3Desc: "مراقبة إنجازات طفلك",
      topic4: "أفضل الممارسات",
      topic4Desc: "نصائح للتدريس المنزلي الفعال",
      videoCompleted: "اكتمل التدريب!",
      videoCompletedText: "أنتِ الآن جاهزة لإرسال طلب التسجيل",
      watchToComplete: "شاهدي الفيديو للمتابعة",
      submitRequest: "إرسال طلب التسجيل",
      videoPlaying: "تشغيل الفيديو التدريبي...",
      complete: "مكتمل",
      videoDialogTitle: "الفيديو التدريبي مطلوب",
      startVideo: "ابدأ الفيديو التدريبي",
      congratulations: "مبروك!",
      thankYou: "شكراً لإرسا�� طلب التسجيل",
      underReview:
        "طلبك قيد المراجعة من قبل فريق إدارة خندق. نراجع كل طلب بعناية لضمان أفضل تجربة تعليمية لجميع طلابنا.",
      emailNotification: "إشعار البريد الإلكتروني",
      emailNotificationText:
        "سنرسل بيانات تسجيل الدخول إلى عنوان بريدك الإلكتروني المسجل",
      smsNotification: "إشعار الرسائل القصيرة",
      smsNotificationText:
        "قد تتلقين أيضاً تأكيداً عبر الرسائل القصيرة (إذا تم توفير رقم الهاتف)",
      whatHappensNext: "ماذا يحدث بعد ذلك؟",
      nextStep1: "فريق الإدارة يراجع طلبك",
      nextStep2: "الموافقة على الحساب (خلال 3 أيام)",
      nextStep3:
        "إرسال بيانات الدخول عبر البريد الإلكتروني أو الرسائل القصيرة",
      nextStep4: "ابدأي رحلة التعليم الإسلامي لطفلك!",
      stayTuned: "ابقي على اطلاع!",
      contactSoon: "سنتصل بك في الأيام الثلاثة القادمة",
    },
    login: {
      title: "تسجيل الدخول للمتابعة",
      email: "عنوان البريد الإلكتروني",
      emailPlaceholder: "أدخل بريدك الإلكتروني",
      password: "كلمة المرور",
      passwordPlaceholder: "أدخل كلمة المرور",
      loginButton: "تسجيل الدخول",
      newUserNote:
        "يجب على المستخدمين الجدد إكمال عملية طلب التسجيل وانتظار الموافقة",
      seekKnowledge: "اطلبوا العلم من المهد إلى اللحد",
      islamicTeaching: "تعليم إسلامي",
    },
    home: {
      greeting: "السلام عليكم",
      overallProgress: "التقدم الإجمالي",
      complete: "مكتمل",
      activeStudents: "الطلاب النشطون",
      lessonsThisWeek: "دروس هذا الأسبوع",
      recentActivity: "النشاط الأخير",
      upcomingActivities: "الأنشطة القادمة",
      recentAchievements: "الإنجازات الأخيرة",
    },
    lesson: {
      selectChild: "اختر الطفل",
      selectGrade: "اختر مستوى الصف",
      selectSemester: "اختر الفصل الدراسي",
      selectWeek: "اختر الأسبوع",
      weeklySchedule: "الجدول الأسبوعي للفصول",
      dailyClassTimes: "أوقات الفصول اليومية:",
      firstPeriod: "الحصة الأولى: 10:30 - 11:20 (القرآن)",
      secondPeriod:
        "الحصة الثانية: 11:30 - 12:20 (المادة اليومية)",
      currentGrade: "الصف الحالي",
      addChild: "إضافة طفل جديد",
      weeksOfLessons: "أسابيع من الدروس",
      completePrevious: "أكمل الفصل الدراسي السابق لفتح",
      semesterStructure: "هيكل الفصل الدراسي:",
      regularWeeks: "11 أسبوعاً من الدروس المنتظمة",
      revisionWeek: "أسبوع واحد للمراجعة والتحضير للاختبار",
      testWeek: "أسبوع واحد للاختبارات",
      regularLesson: "الأسبوع",
      revisionWeekLabel: "أسبوع المراجعة",
      testWeekLabel: "أسبوع الاختبار",
      weekTypes: "أنواع الأسابيع:",
      regularLearning: "أسبوع التعلم المنتظم",
      revisionPrep: "المراجعة والتحضير",
      locked: "مقفل",
      unlockWeek: "فتح الأسبوع",
      progressSequentially: "التقدم بالتسلسل",
      sequentialText:
        "أكمل جميع الدروس في الأسبوع الحالي لفتح الأسبوع التالي. هذا يضمن الفهم الشامل وإتقان كل موضوع.",
      weekLocked: "الأسبوع مقفل",
      weekLockedText:
        "دروس هذا الأسبوع مقفلة حالياً. للوصول إلى الأسبوع {week}، يجب عليك أولاً إكمال جميع الأسابيع السابقة.",
      toUnlockWeek: "لفتح الأسبوع {week}:",
      completeAllDays:
        "أكمل جميع الأيام الستة من الأسبوع {week}",
      finishAllLessons: "أنهِ جميع دروس القرآن والمواد",
      watchVideos: "شاهد جميع مقاطع الفيديو وأكمل الألعاب",
      achieveScores: "حقق الحد الأدنى من الدرجات المطلوبة",
      sequentialLearning:
        "التعلم المتسلسل يضمن بناء طفلك أساساً قوياً في المعرفة الإسلامية قبل التقدم إلى مواضيع جديدة.",
      understood: "فهمت",
      sequentialLearningDay: "التعلم المتسلسل",
      dayLockedText:
        "أكمل درس اليوم لفتح دروس الغد. يتوفر يوم واحد فقط في كل مرة لضمان التقدم المستمر في التعلم.",
      lessonLocked: "الدرس مقفل",
      dayLessonLocked: "درس {day} مقفل حالياً.",
      toUnlockLesson: "لفتح هذا الدرس:",
      completePreviousDay: "أكمل دروس اليوم السابق",
      finishBothPeriods: "أنهِ حصتي القرآن والمادة",
      watchAllVideos: "شاهد جميع مقاطع الفيديو وأكمل الأنشطة",
      strongFoundation:
        "هذا يضمن إتقان طفلك لكل درس قبل المضي قدماً، وبناء أساس قوي في المعرفة الإسلامية.",
      active: "نشط",
      monday: "الإثنين",
      tuesday: "الثلاثاء",
      wednesday: "الأربعاء",
      thursday: "الخميس",
      friday: "الجمعة",
      saturday: "السبت",
    },
    progress: {
      title: "تتبع التقدم",
      overallProgress: "التقدم الإجمالي",
      thisWeek: "هذا الأسبوع",
      achievements: "الإنجازات",
      rank: "الترتيب",
      weeklyActivity: "النشاط الأسبوعي",
      chartComing: "مخطط النشاط قريباً",
    },
    notification: {
      title: "الإشعارات",
      markAllRead: "وضع علامة مقروء للجميع",
      unreadNotifications: "الإشعارات غير المقروءة",
      noNotifications: "لا توجد إشعارات",
      allCaughtUp: "أنت على اطلاع بكل شيء!",
      lessonCompleted: "اكتمل الدرس",
      newWeekUnlocked: "تم فتح أسبوع جديد",
      dailyReminder: "تذكير يومي",
      achievementUnlocked: "تم فتح إنجاز",
    },
    profile: {
      title: "الملف الشخصي",
      memberSince: "عضو منذ",
      email: "البريد الإلكتروني",
      location: "الموقع",
      languages: "اللغات",
      quranLevel: "مستو�� القرآن",
      completed: "مكتمل",
      myChildren: "أطفالي",
      settings: "الإعدادات",
      helpSupport: "المساعدة والدعم",
      logout: "تسجيل الخروج",
      quoteText: "خيركم من تعلم القرآن وعلمه",
      quoteAuthor: "النبي محمد ﷺ",
    },
    subjects: {
      quran: "القرآن",
      hadis: "الحديث",
      fiqh: "الفقه",
      sira: "السيرة",
      arabic: "العربية",
      zikr: "الذكر",
      akhlaq: "الأخلاق",
    },
  },
  am: {
    common: {
      back: "ወደኋላ",
      next: "ቀጣይ",
      finish: "ጨርስ",
      cancel: "ሰርዝ",
      continue: "ቀጥል",
      submit: "አስገባ",
      login: "ግባ",
      logout: "ውጣ",
      save: "አስቀምጥ",
      delete: "ሰርዝ",
      edit: "አርትዕ",
      close: "ዝጋ",
      loading: "በመጫን ላይ...",
      error: "ስህተት",
      success: "ተሳክቷል",
      language: "ቋንቋ",
    },
    greeting: {
      assalamu: "አሰላሙ አለይኩም ወራህመቱላህ ወበረካቱህ",
      arabic:
        "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ",
      meaning: "የአላህ ሰላም፣ ምህረት እና በረከት ከእናንተ ጋር ይሁን",
      welcome: "ወደ ኸንደቅ እንኳን በደህና መጡ",
      peace: "ሰላም ከእናንተ ጋር ይሁን",
    },
    info: {
      title: "E-Learning Medresa",
      bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      bismillahMeaning: "በአላህ ስም በጣም ከባድ ነው በጣም አዛኝ",
      missionTitle: "የእኛ ተልዕኮ",
      missionText:
        "ኸንደቅ እናቶች እና ተንከባካቢዎች ልጆቻቸውን በተዋቀረ የእስላማዊ ትምህርት ጉዞ ለመምራት የሚረዳ አጠቃላይ የእስላማዊ ኤሌክትሮኒክ የመማሪያ መድረክ ነው።",
      feature1Title: "አጠቃላይ ስርዓተ ትምህርት",
      feature1Text:
        "ቁርአን፣ ሐዲስ፣ ፊቅህ፣ ስራ፣ አረብኛ፣ ዚክር እና አህላቅን የሚሸፍኑ 10 የክፍል ደረጃዎች",
      feature2Title: "በእናት የሚመራ ትምህርት",
      feature2Text: "እናቶች በቤት ውስጥ የልጆቻቸው ዋና አስተማሪዎች እንዲሆኑ ማብቃት",
      feature3Title: "የእድገት ክትትል",
      feature3Text: "የልጅዎን ስኬቶች ይከታተሉ እና አብረው ክብረ በዓላትን ያክብሩ",
      feature4Title: "ማራኪ ይዘት",
      feature4Text:
        "ትምህርትን አስደሳች ለማድረግ ቪዲዮዎች፣ የመማሪያ መጽሐፍት እና በይነተገናኝ ጨዋታዎች",
      whatsIncluded: "የተካተቱት",
      include1: "ከቪዲዮ ይዘት ጋር ዕለታዊ የተዋቀሩ ትምህርቶች",
      include2: "አጠቃላይ የመማሪያ መጽሐፍ ቁሳቁሶች",
      include3: "በይነተገናኝ ጨዋታዎች እና እንቅስቃሴዎች",
      include4: "የእድገት ክትትል እና የስኬት ስርዓት",
      include5: "ማሳወቂያዎች እና አስታዋሾች",
      include6: "ለእያንዳንዱ ልጅ የተበጀ መገለጫ",
      quoteText:
        "ከእናንተ መካከል በጣም ጥሩዎች ቁርአንን የሚማሩ እና የሚያስተምሩት ናቸው።",
      quoteAuthor: "ነብይ ሙሐመድ ﷺ (ሳሂህ አል-ቡኻሪ)",
      registerButton: "የምዝገባ ጥያቄ ይላኩ",
      getStartedButton: "ጀምር",
    },
    registration: {
      step1Title: "የተንከባካቢ መረጃ",
      step2Title: "የስልጠና ቪዲዮ",
      step1Of2: "ደረጃ 1 ከ 2",
      step2Of2: "ደረጃ 2 ከ 2",
      profilePhoto: "የመገለጫ ፎቶ",
      fullName: "ሙሉ ስም",
      fullNamePlaceholder: "ሙሉ ስምዎን ያስገቡ",
      age: "ዕድሜ",
      agePlaceholder: "ዕድሜ",
      gender: "ጾታ",
      genderSelect: "ምረጥ",
      female: "ሴት",
      male: "ወንድ",
      other: "ሌላ",
      role: "ሚና",
      roleSelect: "ሚናዎን ይምረጡ",
      mother: "እናት",
      father: "አባት",
      caretaker: "ተንከባካቢ",
      sibling: "ወንድም/እህት",
      otherRole: "ሌላ",
      location: "አካባቢ",
      continent: "አህጉር",
      selectContinent: "አህጉር ምረጥ",
      country: "ሀገር",
      countryPlaceholder: "ሀገር",
      contactInfo: "የመገናኛ መረጃ",
      email: "ኢሜይል አድራሻ",
      emailPlaceholder: "ኢሜይል አድራሻ",
      phone: "ስልክ ቁጥር (አማራጭ)",
      phonePlaceholder: "ስልክ ቁጥር (አማራጭ)",
      languages: "ቋንቋዎች (ሁሉንም ተገቢውን ይምረጡ)",
      amharic: "አማርኛ",
      english: "እንግሊዝኛ",
      arabic: "አረብኛ",
      oromo: "ኦሮምኛ",
      quranLevel: "የቁርአን ደረጃ (የተጠናቀቁ ክፍሎች)",
      suitableTime: "ልጅን ለመምራት ተስማሚ ጊዜ",
      suitableTimePlaceholder: "ለምሳሌ፦ ጠዋት 10:00 - 12:00",
      expectations: "ከኸንደቅ የሚጠበቁ ነገሮች",
      expectationsPlaceholder: "የሚጠበቁ ነገሮችዎን እና ግቦችዎን ያጋሩ...",
      loginCredentials: "የመግቢያ ምስክርነቶች",
      username: "የተመረጠ የተጠቃሚ ስም",
      usernamePlaceholder: "የተመረጠ የተጠቃሚ ስም",
      password: "የይለፍ ቃል",
      passwordPlaceholder: "የይለፍ ቃል",
      credentialsNote:
        "ይህ የተጠቃሚ ስም እና የይለፍ ቃል ከፈቀደ በኋላ ለመግባት ይጠቀማሉ",
      continueStep2: "ወደ ደረጃ 2 ቀጥል",
      backToStep1: "ወደ ደረጃ 1 ተመለስ",
      trainingRequired: "ስልጠና ያስፈልጋል",
      trainingRequiredText:
        "የምዝገባ ጥያቄዎን ለማጠናቀቅ የመግቢያ እና የማብራሪያ የስልጠና ቪዲዮውን መመልከት አለብዎት። ይህ ቪዲዮ ኸንደቅን በብቃት የልጆችዎን የእስላማዊ ትምህርት ለመምራት እንዴት እንደሚጠቀሙ እንዲገነዘቡ ይረዳዎታል።",
      videoTitle: "ወደ ኸንደቅ መግቢያ",
      videoSubtitle: "ልጆችዎን በእስላማዊ ትምህርት ጉዞ እንዴት እንደሚመሩ ይማሩ",
      whatYouLearn: "የሚማሩት፦",
      topic1: "የመድረክ አጠቃላይ እይታ",
      topic1Desc: "የኸንደቅ በይነገጽን መረዳት",
      topic2: "ዕለታዊ የትምህርት አወቃቀር",
      topic2Desc: "ዕለታዊ የእስላማዊ ትምህርቶችን እንዴት እንደሚያካሂዱ",
      topic3: "የእድገት ክትትል",
      topic3Desc: "የልጅዎን ስኬቶች መከታተል",
      topic4: "ምርጥ ልምዶች",
      topic4Desc: "ለውጤታማ የቤት ማስተማር ምክሮች",
      videoCompleted: "ስልጠናው ተጠናቋል!",
      videoCompletedText: "አሁን የምዝገባ ጥያቄዎን ለማስገባት ዝግጁ ነዎት",
      watchToComplete: "ለመቀጠል ቪዲዮውን ይመልከቱ",
      submitRequest: "የምዝገባ ጥያቄ ያስገቡ",
      videoPlaying: "የስልጠና ቪዲዮ በመጫወት ላይ...",
      complete: "ተጠናቅቋል",
      videoDialogTitle: "የስልጠና ቪዲዮ ያስፈልጋል",
      startVideo: "የስልጠና ቪዲዮ ጀምር",
      congratulations: "እንኳን ደስ አለዎት!",
      thankYou: "የምዝገባ ጥያቄዎን ስላስገቡ እናመሰግናለን",
      underReview:
        "ጥያቄዎ በኸንደቅ አስተዳዳሪ ቡድን በመገምገም ላይ ነው። ለሁሉም ተማሪዎች ምርጡን የመማሪያ ልምድ ለማረጋገጥ እያንዳንዱን ማመልከቻ በጥንቃቄ እንገመግማለን።",
      emailNotification: "የኢሜይል ማሳወቂያ",
      emailNotificationText:
        "የመግቢያ ምስክርነቶችዎን ወደ የተመዘገበው ኢሜይል አድራሻዎ እንልካለን",
      smsNotification: "የኤስኤምኤስ ማሳወቂያ",
      smsNotificationText:
        "በተጨማሪም የቴክስት መልእክት ማረጋገጫ ሊደርስዎ ይችላል (የስልክ ቁጥር ከቀረበ)",
      whatHappensNext: "በመቀጠል ምን ይከሰታል?",
      nextStep1: "የአስተዳዳሪ ቡድን ማመልከቻዎን ይገመግማል",
      nextStep2: "የሂሳብ ማረጋገጫ (በ3 ቀናት ውስጥ)",
      nextStep3: "የመግቢያ ምስክርነቶች በኢሜይል ወይም በኤስኤምኤስ ይላካሉ",
      nextStep4: "የልጅዎን የእስላማዊ ትምህርት ጉዞ ይጀምሩ!",
      stayTuned: "መከታተል ይቀጥሉ!",
      contactSoon: "በሚቀጥሉት 3 ቀናት እናገኝዎታለን",
    },
    login: {
      title: "ለመቀጠል ይግቡ",
      email: "ኢሜይል አድራሻ",
      emailPlaceholder: "ኢሜይልዎን ያስገቡ",
      password: "የይለፍ ቃል",
      passwordPlaceholder: "የይለፍ ቃልዎን ያስገቡ",
      loginButton: "ግባ",
      newUserNote:
        "አዲስ ተጠቃሚዎች የምዝገባ ጥያቄ ሂደቱን መጨረስ እና ፈቃድን መጠበቅ አለባቸው",
      seekKnowledge: "እውቀትን ከመወለድ እስከ መቃብር ድረስ ፈልጉ",
      islamicTeaching: "የኢስላም ትምህርት",
    },
    home: {
      greeting: "አሰላሙ አለይኩም",
      overallProgress: "አጠቃላይ እድገት",
      complete: "ተጠናቅቋል",
      activeStudents: "ንቁ ተማሪዎች",
      lessonsThisWeek: "በዚህ ሳምንት ትምህርቶች",
      recentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
      upcomingActivities: "የሚመጡ እንቅስቃሴዎች",
      recentAchievements: "የቅርብ ጊዜ ስኬቶች",
    },
    lesson: {
      selectChild: "ልጅ ይምረጡ",
      selectGrade: "የክፍል ደረጃ ይምረጡ",
      selectSemester: "ሴሚስተር ይምረጡ",
      selectWeek: "ሳምንት ይምረጡ",
      weeklySchedule: "ሳምንታዊ የክፍል መርሐግብር",
      dailyClassTimes: "ዕለታዊ የክፍል ጊዜዎች፦",
      firstPeriod: "የመጀመሪያ ጊዜ፦ 10:30 - 11:20 (ቁርአን)",
      secondPeriod: "ሁለተኛ ጊዜ፦ 11:30 - 12:20 (ዕለታዊ ትምህርት)",
      currentGrade: "የአሁኑ ክፍል",
      addChild: "አዲስ ልጅ ያክሉ",
      weeksOfLessons: "ሳምንታት የትምህርቶች",
      completePrevious: "ለመክፈት ቀዳሚውን ሴሚስተር ያጠናቅቁ",
      semesterStructure: "የሴሚስተር አወቃቀር፦",
      regularWeeks: "11 ሳምንታት መደበኛ ትምህርቶች",
      revisionWeek: "1 ሳምንት ለክለሳ እና ለፈተና ዝግጅት",
      testWeek: "1 ሳምንት ለፈተናዎች",
      regularLesson: "ሳምንት",
      revisionWeekLabel: "የክለሳ ሳምንት",
      testWeekLabel: "የፈተና ሳምንት",
      weekTypes: "የሳምንት አይነቶች፦",
      regularLearning: "መደበኛ የመማሪያ ሳምንት",
      revisionPrep: "ክለሳ እና ዝግጅት",
      locked: "ተቆልፏል",
      unlockWeek: "ሳምንት ክፈት",
      progressSequentially: "በቅደም ተከተል ግስጋሴ ያድርጉ",
      sequentialText:
        "ቀጣዩን ለመክፈት በአሁኑ ሳምንት ውስጥ ያሉትን ሁሉንም ትምህርቶች ያጠናቅቁ። ይህ የእያንዳንዱን ርዕስ አጠቃላይ ግንዛቤ እና ችሎታን ያረጋግጣል።",
      weekLocked: "ሳምንት ተቆልፏል",
      weekLockedText:
        "የዚህ ሳምንት ትምህርቶች በአሁኑ ጊዜ ተቆልፈዋል። ሳምንት {week} ለማግኘት በመጀመሪያ ቀዳሚ ሳምንታትን ማጠናቀቅ አለብዎት።",
      toUnlockWeek: "ሳምንት {week} ለመክፈት፦",
      completeAllDays: "ሳምንት {week} ሁሉንም 6 ቀናት ያጠናቅቁ",
      finishAllLessons: "ሁሉንም የቁርአን እና የትምህርት ትምህርቶች ያጠናቅቁ",
      watchVideos: "ሁሉንም ቪዲዮዎች ይመልከቱ እና ጨዋታዎችን ያጠናቅቁ",
      achieveScores: "ዝቅተኛው ማለፊያ ውጤቶችን ማሳካት",
      sequentialLearning:
        "ተከታታይ መማር ልጅዎ ወደ አዲስ ርዕሶች ከመሄዱ በፊት በእስላማዊ እውቀት ላይ ጠንካራ መሰረት መገንባቱን ያረጋግጣል።",
      understood: "ተረድቻል",
      sequentialLearningDay: "ተከታታይ መማር",
      dayLockedText:
        "የነገን ትምህርቶች ለመክፈት የዛሬን ትምህርት ያጠናቅቁ። ቀጣይነት ያለው የመማሪያ እድገትን ለማረጋገጥ በአንድ ጊዜ አንድ ቀን ብቻ ይገኛል።",
      lessonLocked: "ትምህርት ተቆልፏል",
      dayLessonLocked: "{day} ትምህርት በአሁኑ ጊዜ ተቆልፏል።",
      toUnlockLesson: "ይህን ትምህርት ለመክፈት፦",
      completePreviousDay: "ቀዳሚውን ቀን ትምህርቶች ያጠናቅቁ",
      finishBothPeriods: "ሁለቱንም የቁርአን እና የትምህርት ጊዜዎች ያጠናቅቁ",
      watchAllVideos: "ሁሉንም ቪዲዮዎች ይመልከቱ እና እንቅስቃሴዎችን ያጠናቅቁ",
      strongFoundation:
        "ይህ ልጅዎ ወደ ፊት ከመሄዱ በፊት እያንዳንዱን ትምህርት እንዲይዝ፣ በእስላማዊ እውቀት ላይ ጠንካራ መሰረት እንዲገነባ ያረጋግጣል።",
      active: "ንቁ",
      monday: "ሰኞ",
      tuesday: "ማክሰኞ",
      wednesday: "ረቡዕ",
      thursday: "ሐሙስ",
      friday: "አርብ",
      saturday: "ቅዳሜ",
    },
    progress: {
      title: "የእድገት ክትትል",
      overallProgress: "አጠቃላይ እድገት",
      thisWeek: "በዚህ ሳምንት",
      achievements: "ስኬቶች",
      rank: "ደረጃ",
      weeklyActivity: "ሳምንታዊ እንቅስቃሴ",
      chartComing: "የእንቅስቃሴ ገበታ በቅርቡ",
    },
    notification: {
      title: "ማሳወቂያዎች",
      markAllRead: "ሁሉንም እንደተነበበ ምልክት አድርግ",
      unreadNotifications: "ያልተነበቡ ማሳወቂያዎች",
      noNotifications: "ማሳወቂያዎች የሉም",
      allCaughtUp: "ሁሉንም አላገኙ!",
      lessonCompleted: "ትምህርት ተጠናቋል",
      newWeekUnlocked: "አዲስ ሳምንት ተከፍቷል",
      dailyReminder: "ዕለታዊ አስታዋሽ",
      achievementUnlocked: "ስኬት ተከፍቷል",
    },
    profile: {
      title: "መገለጫ",
      memberSince: "አባል ከ",
      email: "ኢሜይል",
      location: "አካባቢ",
      languages: "ቋንቋዎች",
      quranLevel: "የቁርአን ደረጃ",
      completed: "ተጠናቋል",
      myChildren: "ልጆቼ",
      settings: "ቅንብሮች",
      helpSupport: "እገዛ እና ድጋፍ",
      logout: "ውጣ",
      quoteText:
        "ከእናንተ መካከል በጣም ጥሩዎች ቁርአንን የሚማሩ እና የሚያስተምሩት ናቸው።",
      quoteAuthor: "ነብይ ሙሐመድ ﷺ",
    },
    subjects: {
      quran: "ቁርአን",
      hadis: "ሐዲስ",
      fiqh: "ፊቅህ",
      sira: "ስራ",
      arabic: "አረብኛ",
      zikr: "ዚክር",
      akhlaq: "አህላቅ",
    },
  },
  om: {
    common: {
      back: "Duubatti",
      next: "Itti Aanuu",
      finish: "Xumuri",
      cancel: "Haqqi",
      continue: "Itti Fufi",
      submit: "Galchi",
      login: "Seeni",
      logout: "Ba'i",
      save: "Olkaa'i",
      delete: "Haqqi",
      edit: "Gulaal",
      close: "Cuffi",
      loading: "Fe'amaa jira...",
      error: "Dogoggora",
      success: "Milkaa'ina",
      language: "Afaan",
    },
    greeting: {
      assalamu:
        "Assalaamu Aleykum warahmatu laahi wabarakaatuh",
      arabic:
        "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ",
      meaning:
        "Nagaan, araaraa fi eebbaan Rabbii isin waliin haa ta'u",
      welcome: "Gara Khendeq baga nagaan dhuftan",
      peace: "Nagaan isin waliin haa ta'u",
    },
    info: {
      title: "Barnoota Islaamaa Elektirooniksii Daa'immaniif",
      bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      bismillahMeaning:
        "Maqaa Rabbiin Araaraa Qabeessa, Jaalala Guddaa Qabeessa",
      missionTitle: "Ergama Keenya",
      missionText:
        "Khendeq waltajjii barnoota elektirooniksii Islaamaa bal'aa haadhoolii fi kunuunsitoota ijoollee isaanii karaa barnoota Islaamaa caaseffame akka qajeelchan gargaaruuf qophaa'edha.",
      feature1Title: "Kaarikulamii Bal'aa",
      feature1Text:
        "Sadarkaa kutaa 10, Qur'aana, Hadiisa, Fiqha, Siirata, Arabiffaa, Dhikra, fi Akhlaaqa of keessaa qaba",
      feature2Title: "Barnoota Haadhaan Geggeeffamu",
      feature2Text:
        "Haadhoolii barsiisota jalqabaa ijoollee isaanii mana keessatti akka ta'aniif humna kennuu",
      feature3Title: "Hordoffii Guddina",
      feature3Text:
        "Milkaa'ina daa'ima keessanii hordofaa fi wajjin kabajaa ayyaanaa",
      feature4Title: "Qabiyyee Hawwataa",
      feature4Text:
        "Viidiyoo, kitaabota barnoota, fi tapha wal qunnamtii qabuun barumsaa gammachiisaa ta'e",
      whatsIncluded: "Wanti Hammatame",
      include1:
        "Barnoota guyyaa guyyaa qabiyyee viidiyoo waliin caaseffame",
      include2: "Meeshaalee kitaaba barnoota bal'aa",
      include3: "Taphaa fi sochii wal qunnamtii qabu",
      include4: "Sirna hordoffii guddina fi milkaa'ina",
      include5: "Beeksisaa fi yaadachiisa",
      include6:
        "Dhuunfachiisuun profaayilii tokkoon tokkoo daa'imaatiif",
      quoteText:
        "Isin keessaa kan gaarii ta'e kan Qur'aana baratee barsiisudha.",
      quoteAuthor: "Nabiyyii Muhammad ﷺ (Sahih al-Bukhari)",
      registerButton: "Gaaffii Galmee Ergaa",
      getStartedButton: "Jalqabi",
    },
    registration: {
      step1Title: "Odeeffannoo Kunuunsitootaa",
      step2Title: "Viidiyoo Leenjii",
      step1Of2: "Tarkaanfii 1 of 2",
      step2Of2: "Tarkaanfii 2 of 2",
      profilePhoto: "Suuraa Profaayilii",
      fullName: "Maqaa Guutuu",
      fullNamePlaceholder: "Maqaa guutuu keessan galchaa",
      age: "Umurii",
      agePlaceholder: "Umurii",
      gender: "Saala",
      genderSelect: "Filadhu",
      female: "Dubartii",
      male: "Dhiira",
      other: "Kan biraa",
      role: "Gahee",
      roleSelect: "Gahee keessan filadhu",
      mother: "HAADHA",
      father: "ABBAA",
      caretaker: "KUNUUNSITUU",
      sibling: "OBBOLEESSA",
      otherRole: "KAN BIRAA",
      location: "Bakka",
      continent: "Kontinentii",
      selectContinent: "Kontinentii Filadhu",
      country: "Biyya",
      countryPlaceholder: "Biyya",
      contactInfo: "Odeeffannoo Quunnamtii",
      email: "Teessoo imeelii",
      emailPlaceholder: "Teessoo imeelii",
      phone: "Lakkoofsa bilbilaa (filannoorraa)",
      phonePlaceholder: "Lakkoofsa bilbilaa (filannoorraa)",
      languages: "Afaanota (Hundumaa kan mijatu filadhu)",
      amharic: "AFAAN AMAARAA",
      english: "AFAAN INGILIZII",
      arabic: "AFAAN ARABIFFAA",
      oromo: "AFAAN OROMOO",
      quranLevel: "Sadarkaa Qur'aanaa (Juz Xumuraman)",
      suitableTime: "Yeroo Daa'ima Qajeelchuuf Mijatu",
      suitableTimePlaceholder:
        "Fakkeenyaf: Ganama 10:00 - 12:00",
      expectations: "Wanta Khendeq irraa Eegdan",
      expectationsPlaceholder:
        "Wanta eegdanii fi kaayyoo qooddadhaa...",
      loginCredentials: "Ragaalee Seensaa",
      username: "Maqaa Fayyadamaa Filatamaa",
      usernamePlaceholder: "Maqaa Fayyadamaa Filatamaa",
      password: "Jecha Iccitii",
      passwordPlaceholder: "Jecha Iccitii",
      credentialsNote:
        "Maqaan fayyadamaa fi jecha iccitii kun erga hayyamamee booda seenuuf itti fayyadamu",
      continueStep2: "Gara Tarkaanfii 2 itti fufi",
      backToStep1: "Gara Tarkaanfii 1 deebi'i",
      trainingRequired: "Leenjii Barbachisoodha",
      trainingRequiredText:
        "Gaaffii galmee keessan xumuuruuf, viidiyoo leenjii seensa fi ibsituu ilaaluu qabdu. Viidiyoon kun Khendeq bu'a qabeessaan itti fayyadamuun barnoota Islaamaa ijoollee keessanii akkamitti akka qajeelchitan akka hubattan isin gargaara.",
      videoTitle: "Seensa gara Khendeq",
      videoSubtitle:
        "Ijoollee keessan imala barnoota Islaamaa keessatti akkamitti akka qajeelchitan baradhaa",
      whatYouLearn: "Wanta Barattu:",
      topic1: "Ilaalcha Waltajjichaa",
      topic1Desc: "Walqunnamtii Khendeq hubachuu",
      topic2: "Caaseffama Barnoota Guyyaa",
      topic2Desc:
        "Barnoota Islaamaa guyyaa akkamitti gaggeessuu",
      topic3: "Hordoffii Guddina",
      topic3Desc: "Milkaa'ina daa'ima keessanii hordofuu",
      topic4: "Amalawwan Gaariin",
      topic4Desc: "Gorsaa barsiisa mana bu'a qabeessaa ta'eef",
      videoCompleted: "Leenjiin Xumurame!",
      videoCompletedText:
        "Amma gaaffii galmee keessan galchuuf qophii dha",
      watchToComplete: "Itti Fufuuf Viidiyoo Ilaalaa",
      submitRequest: "Gaaffii Galmee Galchaa",
      videoPlaying: "Viidiyoon Leenjii Taphachaa jira...",
      complete: "Xumurame",
      videoDialogTitle: "Viidiyoo Leenjii Barbachisoodha",
      startVideo: "Viidiyoo Leenjii Jalqabi",
      congratulations: "Baga Gammaddan!",
      thankYou:
        "Gaaffii galmee keessan ergitanii ni galateeffanna",
      underReview:
        "Gaaffiin keessan garee bulchiinsaa Khendeq keessatti ilaalama keessa jira. Muuxannoo barnoota gaarii hundaaf mirkaneessuuf iyyata tokko tokkoo of eeggannoo guutuun ni ilaalla.",
      emailNotification: "Beeksisa Imeelii",
      emailNotificationText:
        "Ragaalee seensaa keessanii gara teessoo imeelii keessanii galmeeffametti ni ergina",
      smsNotification: "Beeksisa SMS",
      smsNotificationText:
        "Akkasumas mirkaneessa ergaa barreeffamaa argachuu dandeessu (yoo lakkoofsi bilbilaa kenname)",
      whatHappensNext: "Itti Aanuun Maal Ta'a?",
      nextStep1: "Gareen bulchiinsaa iyyata keessan ni ilaala",
      nextStep2: "Hayyama herrega (guyyoota 3 keessatti)",
      nextStep3:
        "Ragaaleen seensaa karaa imeelii ykn SMS ergamu",
      nextStep4:
        "Imala barnoota Islaamaa daa'ima keessanii jalqabaa!",
      stayTuned: "Hordofaa turaa!",
      contactSoon: "Guyyoota 3 dhufan keessatti isin qunnamna",
    },
    login: {
      title: "Itti Fufuuf Seenaa",
      email: "Teessoo Imeelii",
      emailPlaceholder: "Imeelii keessan galchaa",
      password: "Jecha Iccitii",
      passwordPlaceholder: "Jecha iccitii keessan galchaa",
      loginButton: "Seeni",
      newUserNote:
        "Fayyadamtoonni haaraan adeemsa gaaffii galmee xumuuruu fi hayyama eeguu qabu",
      seekKnowledge:
        "Beekumsa dhaloota irraa hanga awwaalaatti barbaadaa",
      islamicTeaching: "Barsiisa Islaamaa",
    },
    home: {
      greeting: "Assalaamu Aleykum",
      overallProgress: "Guddina Waliigalaa",
      complete: "Xumurame",
      activeStudents: "Barattoonni Ka'aman",
      lessonsThisWeek: "Barnootawwan Torbee Kanaa",
      recentActivity: "Sochiiwwan Yeroo Dhiyoo",
      upcomingActivities: "Sochiiwwan Dhufan",
      recentAchievements: "Milkaa'inawwan Yeroo Dhiyoo",
    },
    lesson: {
      selectChild: "Daa'ima Filadhu",
      selectGrade: "Sadarkaa Kutaa Filadhu",
      selectSemester: "Semesteriin Filadhu",
      selectWeek: "Torban Filadhu",
      weeklySchedule: "Sagantaa Kutaa Torbanii",
      dailyClassTimes: "Yeroo Kutaa Guyyaa:",
      firstPeriod: "Yeroo Jalqabaa: 10:30 - 11:20 (Qur'aana)",
      secondPeriod:
        "Yeroo Lammaffaa: 11:30 - 12:20 (Barnoota Guyyaa)",
      currentGrade: "Kutaa Ammaa",
      addChild: "Daa'ima Haaraa Ida'aa",
      weeksOfLessons: "torbeewwan barnootaa",
      completePrevious: "Banuu semesteriin dura xumuruu",
      semesterStructure: "Caasaa Semesteriin:",
      regularWeeks: "11 torbeewwan barnootaa idilee",
      revisionWeek:
        "Torban 1 irra deebi'ii fi qophii qormaataaf",
      testWeek: "Torban 1 qormaatotaaf",
      regularLesson: "Torban",
      revisionWeekLabel: "Torban Irra Deebi'ii",
      testWeekLabel: "Torban Qormaataa",
      weekTypes: "Gosoota Torbanii:",
      regularLearning: "Torban Barumsaa Idilee",
      revisionPrep: "Irra Deebi'ii fi Qophii",
      locked: "Cufameera",
      unlockWeek: "Torban Banaa",
      progressSequentially: "Tartiibaan Guddadhaa",
      sequentialText:
        "Kan itti aanu banuuf torban ammaa keessatti barnootawwan hunda xumuruu. Kun hubannoo guutuu fi ogummaa tokkoon tokkoo mata dureewwaa mirkaneessa.",
      weekLocked: "Torban Cufameera",
      weekLockedText:
        "Barnootawwan torban kanaa yeroo ammaa cufamaniiru. Torban {week} bira ga'uuf, jalqaba torbeewwan duraa hunda xumuuruu qabdu.",
      toUnlockWeek: "Torban {week} banuuf:",
      completeAllDays: "Guyyoota 6 hunda Torban {week} xumuraa",
      finishAllLessons:
        "Barnootawwan Qur'aanaa fi barnoota hunda xumurii",
      watchVideos:
        "Viidiyoowwan hunda ilaalii fi taphawwan xumuraa",
      achieveScores: "Qabxii darbuu gadaanaa argamsiisuu",
      sequentialLearning:
        "Barumsaan tartiibaan daa'imni keessan mata dureewwan haaratti osoo hin darbin beekumsa Islaamaa irratti bu'uura cimaa akka ijaaru mirkaneessa.",
      understood: "Hubadheera",
      sequentialLearningDay: "Barumsaa Tartiibaan",
      dayLockedText:
        "Barnootawwan boru banuuf barnoota har'aa xumuraa. Guddina barnoota wal irraa hin cinneen mirkaneessuuf yeroo tokkotti guyyaa tokko qofa ni argama.",
      lessonLocked: "Barnootni Cufameera",
      dayLessonLocked: "Barnootni {day} yeroo ammaa cufameera.",
      toUnlockLesson: "Barnoota kana banuuf:",
      completePreviousDay: "Barnootawwan guyyaa duraa xumuraa",
      finishBothPeriods:
        "Yeroolee Qur'aanaa fi barnoota lamaanuu xumuraa",
      watchAllVideos:
        "Viidiyoowwan hunda ilaalii fi sochiiwwan xumuraa",
      strongFoundation:
        "Kun daa'imni keessan osoo hin darbin barnoota tokkoon tokkoo akka qabatu, beekumsa Islaamaa irratti bu'uura cimaa akka ijaaru mirkaneessa.",
      active: "Ka'aa",
      monday: "Wiixata",
      tuesday: "Kibxata",
      wednesday: "Roobii",
      thursday: "Kamisa",
      friday: "Jimaata",
      saturday: "Sanbata",
    },
    progress: {
      title: "Hordoffii Guddina",
      overallProgress: "Guddina Waliigalaa",
      thisWeek: "Torbee Kana",
      achievements: "Milkaa'inawwan",
      rank: "Sadarkaa",
      weeklyActivity: "Sochii Torbanii",
      chartComing: "Taattoon sochiiwwanii dhiyoo",
    },
    notification: {
      title: "Beeksisawwan",
      markAllRead: "Hunda akka dubbifametti mallatteessi",
      unreadNotifications: "Beeksisawwan Hin Dubbifamne",
      noNotifications: "Beeksisawwan hin jiran",
      allCaughtUp: "Hunda qabdee jirta!",
      lessonCompleted: "Barnootni Xumurame",
      newWeekUnlocked: "Torban Haaraa Banameera",
      dailyReminder: "Yaadachiisa Guyyaa",
      achievementUnlocked: "Milkaa'ina Banameera",
    },
    profile: {
      title: "Profaayilii",
      memberSince: "Miseensa erga",
      email: "Imeelii",
      location: "Bakka",
      languages: "Afaanota",
      quranLevel: "Sadarkaa Qur'aanaa",
      completed: "Xumurame",
      myChildren: "Ijoollee Koo",
      settings: "Qindaa'ina",
      helpSupport: "Gargaarsa fi Deggarsaa",
      logout: "Ba'ii",
      quoteText:
        "Keessan keessaa kan gaariin kan Qur'aana baratee barsiisudha.",
      quoteAuthor: "Nabiyyii Muhammad ﷺ",
    },
    subjects: {
      quran: "Qur'aana",
      hadis: "Hadiisa",
      fiqh: "Fiqha",
      sira: "Siirata",
      arabic: "Arabiffaa",
      zikr: "Dhikra",
      akhlaq: "Akhlaaqa",
    },
  },
  so: {
    common: {
      back: "Dib",
      next: "Xiga",
      finish: "Dhamays",
      cancel: "Jooji",
      continue: "Sii wad",
      submit: "Soo dir",
      login: "Gal",
      logout: "Ka bax",
      save: "Kaydi",
      delete: "Tirtir",
      edit: "Wax ka beddel",
      close: "Xir",
      loading: "Waa la soo rarayo...",
      error: "Qalad",
      success: "Guul",
      language: "Luqad",
    },
    greeting: {
      assalamu:
        "Assalaamu caleykum warahmatullaahi wabarakaatuh",
      arabic:
        "السَّلاَمُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ",
      meaning:
        "Nabadda, naxariista, iyo barakada Alle ha idinla jirto",
      welcome: "Ku soo dhawoow Khendeq",
      peace: "Nabadi ha idinla jirto",
    },
    info: {
      title:
        "Waxbarashada Islaamka ee Carruurta Elektaroonigga ah",
      bismillah: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
      bismillahMeaning: "Bismillaahi Raxmaani Raxiim",
      missionTitle: "Ujeedada Xarunta",
      missionText:
        "Khendeq waa marinka wax barasho Islaamka ee dhammaystiran oo loogu talagalay in lagu caawiyo hooyooyinka iyo daryeelayaasha in ay carruurtooda ku hagaan socdaal waxbarasho Islaamka oo habaynsan.",
      feature1Title: "Manhaj Dhammaystiran",
      feature1Text:
        "Heerarka 10 fasalka ah, oo ku saabsan Quraanka, Xadiiska, Fiqhiga, Siirada, Carabi, Dikriga, iyo Akhlaaqda",
      feature2Title: "Waxbarasho Hooyadu Hoggaamiso",
      feature2Text:
        "Awood u siinta hooyooyinka in ay noqdaan macallimiinta koowaad ee carruurtooda guriga",
      feature3Title: "Raadinta Horumarka",
      feature3Text:
        "La soco guulaha ilmahaaga oo ku dabbaaldeg marxaladaha wada jirka ah",
      feature4Title: "Nuxur Soo Jiidanaya",
      feature4Text:
        "Muuqaallo, buugaag waxbarasho, iyo ciyaaro is-dhexgal ah si looga dhigo waxbarashada mid madadaallo leh",
      whatsIncluded: "Waxa Ku Jira",
      include1:
        "Casharrada maalintii oo habaynsan oo leh nuxurka muuqaalka",
      include2:
        "Agabka buugaagta waxbarashada oo dhammaystiran",
      include3: "Ciyaaro iyo waxqabadyo is-dhexgal ah",
      include4: "Nidaamka la socoshada horumarka iyo guulaha",
      include5: "Ogeysiisyo iyo xusuusiyayaal",
      include6: "Profile u gaar ah ilmo kasta",
      quoteText:
        "Kuwa ugu wanaagsan idinka waa kuwa Quraanka barta oo barta.",
      quoteAuthor: "Nebiga Muxamed ﷺ (Saxiix al-Bukhari)",
      registerButton: "Soo Dir Codsiga Diiwaangelinta",
      getStartedButton: "Bilow",
    },
    registration: {
      step1Title: "Macluumaadka Daryeelaha",
      step2Title: "Muuqaalka Tababarka",
      step1Of2: "Tallaabada 1 ee 2",
      step2Of2: "Tallaabada 2 ee 2",
      profilePhoto: "Sawirka Profile-ka",
      fullName: "Magaca Buuxa",
      fullNamePlaceholder: "Geli magacaaga buuxda",
      age: "Da'da",
      agePlaceholder: "Da'da",
      gender: "Jinsiga",
      genderSelect: "Dooro",
      female: "Dheddig",
      male: "Lab",
      other: "Kale",
      role: "Doorka",
      roleSelect: "Dooro doorkaaga",
      mother: "HOOYO",
      father: "AABE",
      caretaker: "DARYEELE",
      sibling: "WALAAL",
      otherRole: "KALE",
      location: "Goobta",
      continent: "Qaaradda",
      selectContinent: "Dooro Qaaradda",
      country: "Waddan",
      countryPlaceholder: "Waddan",
      contactInfo: "Macluumaadka Xiriirka",
      email: "Cinwaanka iimeylka",
      emailPlaceholder: "Cinwaanka iimeylka",
      phone: "Nambarka telefoonka (ikhtiyaari ah)",
      phonePlaceholder: "Nambarka telefoonka (ikhtiyaari ah)",
      languages: "Luuqadaha (Dooro dhammaan kuwa ku habboon)",
      amharic: "AXMAARI",
      english: "INGIRIIS",
      arabic: "CARABI",
      oromo: "OROMO",
      quranLevel: "Heerka Quraanka (Juz ee la dhammaystiray)",
      suitableTime: "Waqtiga Ku Habboon Hagidda Ilmaha",
      suitableTimePlaceholder:
        "Tusaale: Subaxnimo 10:00 - 12:00",
      expectations: "Wixii aad ka filanaysid Khendeq",
      expectationsPlaceholder:
        "La wadaag wixii aad filaysid iyo yoolalkaaga...",
      loginCredentials: "Aqoonsiga Galitaanka",
      username: "Magaca Isticmaale ee la Doortay",
      usernamePlaceholder: "Magaca Isticmaale ee la Doortay",
      password: "Erayga Sirta ah",
      passwordPlaceholder: "Erayga Sirta ah",
      credentialsNote:
        "Magacaan isticmaale iyo erayga sirta ah waxaa loo isticmaali doonaa galitaanka ka dib markii la ogolaado",
      continueStep2: "U sii wad Tallaabada 2",
      backToStep1: "Ku noqo Tallaabada 1",
      trainingRequired: "Tababbar ayaa loo baahan yahay",
      trainingRequiredText:
        "Si aad u dhammaystirto codsigaaga diiwaangelinta, waa inaad daawataa muuqaalka tababarka horudhaca iyo sharraxaadda. Muuqaalkan wuxuu kaa caawin doonaa inaad fahanto sida wax ku qabsi ah loogu isticmaalo Khendeq si aad u hagto waxbarashada Islaamka ee carruurta.",
      videoTitle: "Horu dhac ku saabsan Khendeq",
      videoSubtitle:
        "Baro sida aad carruurta u hagto socdaalka waxbarashada Islaamka",
      whatYouLearn: "Waxaad Baranaysaa:",
      topic1: "Aragti Guud oo Marinka",
      topic1Desc: "Fahmida interface-ka Khendeq",
      topic2: "Qaab dhismeedka Cashar Maalinle",
      topic2Desc:
        "Sida loo qabtaa casharrada Islaamka maalinle",
      topic3: "Raadinta Horumarka",
      topic3Desc: "La socoshada guulaha ilmahaaga",
      topic4: "Hab-maamuuska Wanaagsan",
      topic4Desc:
        "Talooyinka waxbarashada guriga ee wax ku ool ah",
      videoCompleted: "Tababarku waa dhammaday!",
      videoCompletedText:
        "Hadda waxaad diyaar u tahay inaad soo dirto codsigaaga diiwaangelinta",
      watchToComplete: "Daawasho Muuqaalka si aad u sii waddo",
      submitRequest: "Soo Dir Codsiga Diiwaangelinta",
      videoPlaying: "Muuqaalka Tababarka ayaa socda...",
      complete: "Dhammaystiran",
      videoDialogTitle:
        "Muuqaalka Tababarka ayaa loo baahan yahay",
      startVideo: "Bilow Muuqaalka Tababarka",
      congratulations: "Hambalyo!",
      thankYou:
        "Waad ku mahadsan tahay codsigaaga diiwaangelinta",
      underReview:
        "Codsigaagu hadda wuxuu ku jiraa dib u eegista kooxda maamulka Khendeq. Si taxadar leh ayaan u dib u eegaynaa codsiga kasta si aan u hubinno khibradda waxbarashada ugu wanaagsan ardayda oo dhan.",
      emailNotification: "Ogeysiiska Iimaylka",
      emailNotificationText:
        "Waxaan ku soo diri doonnaa aqoonsigaaga galitaanka cinwaanka iimeylkaaga la diiwaangeliyay",
      smsNotification: "Ogeysiiska SMS",
      smsNotificationText:
        "Sidoo kale waxaad heli kartaa xaqiijinta fariinta qoraalka ah (haddii la bixiyo nambarka telefoonka)",
      whatHappensNext: "Maxaa xiga?",
      nextStep1:
        "Kooxda maamulku waxay dib u eegaysaa codsigaaga",
      nextStep2: "Oggolaanshaha koondha (3 maalmood gudahood)",
      nextStep3:
        "Aqoonsiga galitaanka waxaa lagu soo diraa iimaylka ama SMS-ka",
      nextStep4:
        "Bilow socdaalka waxbarashada Islaamka ee ilmahaaga!",
      stayTuned: "Sii raac!",
      contactSoon:
        "3-ka maalmood ee soo socda ayaan kugu soo xiri doonnaa",
    },
    login: {
      title: "Gal si aad u sii waddo",
      email: "Cinwaanka Iimeylka",
      emailPlaceholder: "Geli iimeylkaaga",
      password: "Erayga Sirta ah",
      passwordPlaceholder: "Geli erayga sirta ah",
      loginButton: "Gal",
      newUserNote:
        "Isticmaalayaasha cusub waa inay dhammaystiraan habka codsiga diiwaangelinta oo sugaan oggolaanshaha",
      seekKnowledge:
        "Aqoonta dalba intii aad nool tahay ilaa aad dhimatid",
      islamicTeaching: "Waxbarashada Islaamka",
    },
    home: {
      greeting: "Assalaamu caleykum",
      overallProgress: "Horumarka Guud",
      complete: "Dhammaystiran",
      activeStudents: "Ardayda Firfircoon",
      lessonsThisWeek: "Casharrada Toddobaadkan",
      recentActivity: "Waxqabadka Dhawaan",
      upcomingActivities: "Waxqabadyada Soo socda",
      recentAchievements: "Guulaha Dhawaan",
    },
    lesson: {
      selectChild: "Dooro Ilmaha",
      selectGrade: "Dooro Heerka Fasalka",
      selectSemester: "Dooro Semesterka",
      selectWeek: "Dooro Toddobaadka",
      weeklySchedule: "Jadwalka Fasalka ee Toddobaadlaha ah",
      dailyClassTimes: "Waqtiyada Fasalka Maalinle:",
      firstPeriod: "Waqtiga Kowaad: 10:30 - 11:20 (Quraanka)",
      secondPeriod:
        "Waqtiga Labaad: 11:30 - 12:20 (Mowduuca Maalinle)",
      currentGrade: "Fasalka Hadda",
      addChild: "Ku dar Ilmo Cusub",
      weeksOfLessons: "toddobaadyo oo casharrada ah",
      completePrevious:
        "Dhammaystir semesterka hore si aad u furto",
      semesterStructure: "Qaab dhismeedka Semesterka:",
      regularWeeks: "11 toddobaad oo casharrada caadiga ah",
      revisionWeek:
        "1 toddobaad oo dib u eegis iyo diyaarinta imtixaankaaga",
      testWeek: "1 toddobaad oo imtixaanada",
      regularLesson: "Toddobaad",
      revisionWeekLabel: "Toddobaadka Dib u Eegista",
      testWeekLabel: "Toddobaadka Imtixaanka",
      weekTypes: "Noocyada Toddobaadka:",
      regularLearning: "Toddobaadka Waxbarashada Caadiga ah",
      revisionPrep: "Dib u Eegis & Diyaarinta",
      locked: "Xiran yahay",
      unlockWeek: "Fur Toddobaadka",
      progressSequentially: "Horumarka Isku xigxiga",
      sequentialText:
        "Dhammaystir dhammaan casharrada toddobaadka hadda si aad u furto kan xiga. Tani waxay hubinaysaa fahamka dhammaystiran iyo xirfadda mawduuc kasta.",
      weekLocked: "Toddobaadku waa xiran yahay",
      weekLockedText:
        "Casharrada toddobaadkan hadda waa xiran yihiin. Si aad u hesho Toddobaadka {week}, waa inaad marka hore dhammaystirtaa toddobaadyada hore oo dhan.",
      toUnlockWeek: "Si aad u furto Toddobaadka {week}:",
      completeAllDays:
        "Dhammaystir dhammaan 6-ka maalmood ee Toddobaadka {week}",
      finishAllLessons:
        "Dhammaystir dhammaan casharrada Quraanka iyo mowduuca",
      watchVideos:
        "Daawasho dhammaan muuqaallada oo dhammaystir ciyaaraha",
      achieveScores: "Gaadh dhibcaha ugu yaraan ee gudbista",
      sequentialLearning:
        "Waxbarashada isku xigxiga waxay hubinaysaa in ilmahaagu asaas adag uu ku dhisay aqoonta Islaamka ka hor inta aan u gudbin mowduucyo cusub.",
      understood: "Waan fahmay",
      sequentialLearningDay: "Waxbarashada Isku xigxiga",
      dayLockedText:
        "Dhammaystir cashar maanta si aad u furto casharrada berri. Hal maalin oo keliya ayaa la heli karaa mar kasta si loo hubiyo horumarka waxbarashada joogtada ah.",
      lessonLocked: "Casharku waa xiran yahay",
      dayLessonLocked: "Casharka {day} hadda waa xiran yahay.",
      toUnlockLesson: "Si aad u furto casharkan:",
      completePreviousDay:
        "Dhammaystir casharrada maalinta hore",
      finishBothPeriods:
        "Dhammaystir labada waqti ee Quraanka iyo mowduuca",
      watchAllVideos:
        "Daawasho dhammaan muuqaallada oo dhammaystir waxqabadyada",
      strongFoundation:
        "Tani waxay hubinaysaa in ilmahaagu xirifo cashar kasta ka hor inta aanad u gudbin, isagoo dhisaya asaas adag oo aqoonta Islaamka.",
      active: "Firfircoon",
      monday: "Isniin",
      tuesday: "Talaado",
      wednesday: "Arbaco",
      thursday: "Khamiis",
      friday: "Jimco",
      saturday: "Sabti",
    },
    progress: {
      title: "Raadinta Horumarka",
      overallProgress: "Horumarka Guud",
      thisWeek: "Toddobaadkan",
      achievements: "Guulaha",
      rank: "Darajo",
      weeklyActivity: "Waxqabadka Toddobaadlaha ah",
      chartComing: "Jaantuska waxqabadka dhawaan",
    },
    notification: {
      title: "Ogeysiisyada",
      markAllRead: "U calaamadee dhammaan mid la akhriyay",
      unreadNotifications: "Ogeysiisyada aan la akhriyin",
      noNotifications: "Ogeysiisyo ma jiraan",
      allCaughtUp: "Dhammaan waa lagu soo qaaday!",
      lessonCompleted: "Casharku waa dhammaystiran",
      newWeekUnlocked: "Toddobaad Cusub ayaa la furay",
      dailyReminder: "Xusuusinta Maalinle",
      achievementUnlocked: "Guul ayaa la furay",
    },
    profile: {
      title: "Profile-ka",
      memberSince: "Xubin tan iyo",
      email: "Iimeylka",
      location: "Goobta",
      languages: "Luqadaha",
      quranLevel: "Heerka Quraanka",
      completed: "La Dhammaystiran",
      myChildren: "Carruurtayda",
      settings: "Dejinta",
      helpSupport: "Caawimaada & Taageerada",
      logout: "Ka bax",
      quoteText:
        "Kuwa ugu wanaagsan idinka waa kuwa Quraanka barta oo barta.",
      quoteAuthor: "Nebiga Muxamed ﷺ",
    },
    subjects: {
      quran: "Quraanka",
      hadis: "Xadiiska",
      fiqh: "Fiqhiga",
      sira: "Siirada",
      arabic: "Carabi",
      zikr: "Dikriga",
      akhlaq: "Akhlaaqda",
    },
  },
};